blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/stateful-y/sklearn-wrap/discussions
    about: Please use GitHub Discussions for questions and general discussions
  - name: Documentation
    url: https://sklearn-wrap.readthedocs.io/
    about: Check the documentation for guides and API references
