blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/{{ github_username }}/{{ package_name }}/discussions
    about: Please use GitHub Discussions for questions and general discussions
  - name: Documentation
    url: https://{{ github_username }}.github.io/{{ package_name }}/
    about: Check the documentation for guides and API references
